### PR TITLE
Usage of duration for stat times

### PR DESCRIPTION
**Pull request by singloon**
By using duration for the repository model, you can then introduce a presentation layer to then convert the time to whatever format required.

Also with the current stats query there is an error from the casting for the stat times
```
Data conversion error converting "BIGINT to INTERVAL DAY TO SECOND"; SQL statement:
```

### CODE REVIEW

**Comment by singloon** [comment]
@jacklovett can you add the “hacktoberfest-accepted” label onto the PR?

**Comment by jacklovett** [comment]
> By using duration for the repository model, you can then introduce a presentation layer to then convert the time to whatever format required.
> 
> Also with the current stats query there is an error from the casting for the stat times
> 
> ```
> Data conversion error converting "BIGINT to INTERVAL DAY TO SECOND"; SQL statement:
> ```

Hey @singloon, you mean there is a SQL error previously, or now with your new changes? 

Maybe you can explain more why we would want to use Duration? is there some performance benefits? From what i see we had a String value, which has now been changed to a Duration which i now have to format back into a String with some complex logic and from a quick google potentially bringing in new dependencies.

Great work though, thanks for contributing.

**Comment by singloon** [comment]
`Data conversion error converting "BIGINT to INTERVAL DAY TO SECOND"; SQL statement:`
Hey @jacklovett that was the existing SQL error, when I added the test to retrieve stats from the repository.

Duration is the ISO 8601 representation of a time interval. So the JSON response now returns the ISO 8601 duration in the string format. This means the backend or frontend can then parse that standard format to present as seconds, millis, hours whatever the client prefers.

**Comment by singloon** [comment]
Seems like the postgres container isn't able to start up in the github actions.

Example for parsing the durations from the iso 8601 format with moment.js
https://momentjs.com/docs/#/durations/

Then you can present the info in any format you want e.g. .humanize(), asMinutes(), asSeconds(), etc

**Pull request merged**
